name: Deploy to Deno
on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build step
        run: "pnpm install && pnpm run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: nom-blog
          entrypoint: "https://deno.land/std@0.188.0/http/file_server.ts"
          root: "dist"
